#set maxium allowed speeds
vmax: 0.2 #0.6
vtheta_max: 0.3

#Parameters specifying joystick filter 
influence_radius: 2.0 #[m] distance from robot_center
obstacle_damping_dist: 0.3 # used as slow-down dist
stop_threshold: 0.1 #[m]
use_circumscribed_threshold: 1.35 #[rad/s] scan for obstacles in circumscribed radius of robot even when tube filter is enabled during fast rotations
